### PR TITLE
Update to change in PETSc API for KSPMonitorDefault()

### PR DESCRIPTION
**Pull request by BarrySmith**

### CODE REVIEW

**Comment by amklinv** [comment]
Hello @BarrySmith ,

Thank you for helping us fix this!  Unfortunately, I'm getting a build error with these changes

[amklinv@s995692 build]$ make
[  5%] Built target last_lib
[ 11%] Building CXX object petsc/src/CMakeFiles/xsdkpetsc.dir/BelosPETScSolMgr.cpp.o
In file included from /home/amklinv/IDEAS/xSDKTest/installxSDK/xsdk/petsc/arch-linux2-c-debug/externalpackages/git.trilinos/packages/xSDKTrilinos/petsc/src/BelosPETScSolMgr.cpp:44:0:
/home/amklinv/IDEAS/xSDKTest/installxSDK/xsdk/petsc/arch-linux2-c-debug/externalpackages/git.trilinos/packages/xSDKTrilinos/petsc/src/BelosPETScSolMgr.hpp: In member function ‘Belos::ReturnType Belos::PETScSolMgr<ScalarType, MV, OP>::solve()’:
/home/amklinv/IDEAS/xSDKTest/installxSDK/xsdk/petsc/arch-linux2-c-debug/externalpackages/git.trilinos/packages/xSDKTrilinos/petsc/src/BelosPETScSolMgr.hpp:629:117: error: too few arguments to function ‘PetscErrorCode PetscViewerAndFormatCreate(PetscViewer, PetscViewerFormat, PetscViewerAndFormat*_)’
In file included from /home/amklinv/IDEAS/xSDKTest/xsdk-install/include/petscvec.h:10:0,
                 from /home/amklinv/IDEAS/xSDKTest/xsdk-install/include/petscmat.h:6,
                 from /home/amklinv/IDEAS/xSDKTest/xsdk-install/include/petscpc.h:6,
                 from /home/amklinv/IDEAS/xSDKTest/xsdk-install/include/petscksp.h:6,
                 from /home/amklinv/IDEAS/xSDKTest/installxSDK/xsdk/petsc/arch-linux2-c-debug/externalpackages/git.trilinos/packages/xSDKTrilinos/petsc/src/BelosPETScSolMgr.hpp:74,
                 from /home/amklinv/IDEAS/xSDKTest/installxSDK/xsdk/petsc/arch-linux2-c-debug/externalpackages/git.trilinos/packages/xSDKTrilinos/petsc/src/BelosPETScSolMgr.cpp:44:
/home/amklinv/IDEAS/xSDKTest/xsdk-install/include/petscviewer.h:134:30: note: declared here
make[2]: *_\* [petsc/src/CMakeFiles/xsdkpetsc.dir/BelosPETScSolMgr.cpp.o] Error 1
make[1]: **\* [petsc/src/CMakeFiles/xsdkpetsc.dir/all] Error 2
make: **\* [all] Error 2

**Comment by BarrySmith** [comment]
Sorry, my fault. I am fixing it now but its takes a while to build all of trilinos; as soon as I think I have fixed it I will push my fix and send email.

   Barry

**Comment by BarrySmith** [comment]
I pushed a fix to my branch, you should be able to get from the pull request.

**Comment by amklinv** [comment]
This is my first time accepting a pull request, and I suspect I did it wrong (since this is still open).  You should be able to see your commits on the master branch; is it safe to close this?

**Comment by jwillenbring** [comment]
@amklinv did you follow the "command line instructions" for merging?

**Comment by amklinv** [comment]
> @amklinv did you follow the "command line instructions" for merging?

I followed the first few steps, then spent some time fixing the merge conflicts and some bugs in the BelosPETScSolMgr.hpp file.  I then completely forgot I was dealing with a pull request and pushed as I normally would.

**Comment by bartlettroscoe** [comment]
I can see Barry's commits:

```
[8vt@th232 xSDKTrilinos (master)]$ git log-short --name-status --author=bsmith github/master
995d3cf "fix handling of KSPMonitorSet()"
Author: Barry Smith <bsmith@mcs.anl.gov>
Date:   Tue Apr 5 17:03:03 2016 -0500 (2 hours ago)

M       petsc/src/BelosPETScSolMgr.hpp

176bb31 "fix spelling of source for Trilinos source directory location"
Author: Barry Smith <bsmith@mcs.anl.gov>
Date:   Mon Apr 4 22:51:03 2016 -0500 (2 hours ago)

M       CMakeLists.txt

76b2e1c "Update for new KSPMonitorDefault() usage"
Author: Barry Smith <bsmith@mcs.anl.gov>
Date:   Mon Apr 4 22:35:19 2016 -0500 (2 hours ago)

M       petsc/src/BelosPETScSolMgr.hpp
```

Go ahead and close this.

**Comment by amklinv** [comment]
@BarrySmith I just noticed an issue with this change to the code.  PETSc and valgrind both report errors when KSPDestroy is called.  I discovered this in the Epetra KSP example in xSDKTrilinos, which still gets the correct answer and passes.

==15994== Invalid read of size 4  
==15994==    at 0x2AF94A41: PetscCheckPointer (checkptr.c:106)  
==15994==    by 0x2B01C518: PetscObjectDestroy (destroy.c:71)  
==15994==    by 0x2B01E109: PetscObjectRegisterDestroyAll (destroy.c:251)  
==15994==    by 0x2B051F96: PetscFinalize (pinit.c:1141)  
==15994==    by 0x446D8D: Belos::PETScSolMgr<double, Epetra_MultiVector, Epetra_Operator>::solve() (BelosPETScSolMgr.hpp:711) 
==15994==    by 0x438BF9: main (Epetra_KSPEx.cpp:169)  
==15994==  Address 0x3604b1a0 is 1,600 bytes inside a block of size 2,356 free'd  
==15994==    at 0x4A07430: free (vg_replace_malloc.c:446)  
==15994==    by 0x2B000E24: PetscFreeAlign (mal.c:72)  
==15994==    by 0x2B004000: PetscTrFreeDefault (mtr.c:315)  
==15994==    by 0x2B0D4143: PetscViewerDestroy (view.c:108)
==15994==    by 0x2B0D48B3: PetscViewerAndFormatDestroy (view.c:167)  
==15994==    by 0x2C112063: KSPMonitorCancel (itfunc.c:1807)  
==15994==    by 0x2C109C5C: KSPDestroy (itfunc.c:991)  
==15994==    by 0x446C53: Belos::PETScSolMgr<double, Epetra_MultiVector, Epetra_Operator>::solve() (BelosPETScSolMgr.hpp:700)  
==15994==    by 0x438BF9: main (Epetra_KSPEx.cpp:169)  
==15994==  
==15994== Invalid read of size 4  
==15994==    at 0x2B01C56F: PetscObjectDestroy (destroy.c:71)  
==15994==    by 0x2B01E109: PetscObjectRegisterDestroyAll (destroy.c:251)  
==15994==    by 0x2B051F96: PetscFinalize (pinit.c:1141)  
==15994==    by 0x446D8D: Belos::PETScSolMgr<double, Epetra_MultiVector, Epetra_Operator>::solve() (BelosPETScSolMgr.hpp:711)
==15994==    by 0x438BF9: main (Epetra_KSPEx.cpp:169)  
==15994==  Address 0x3604b1a0 is 1,600 bytes inside a block of size 2,356 free'd  
==15994==    at 0x4A07430: free (vg_replace_malloc.c:446)  
==15994==    by 0x2B000E24: PetscFreeAlign (mal.c:72)  
==15994==    by 0x2B004000: PetscTrFreeDefault (mtr.c:315)  
==15994==    by 0x2B0D4143: PetscViewerDestroy (view.c:108)  
==15994==    by 0x2B0D48B3: PetscViewerAndFormatDestroy (view.c:167)  
==15994==    by 0x2C112063: KSPMonitorCancel (itfunc.c:1807)  
==15994==    by 0x2C109C5C: KSPDestroy (itfunc.c:991)  
==15994==    by 0x446C53: Belos::PETScSolMgr<double, Epetra_MultiVector, Epetra_Operator>::solve() (BelosPETScSolMgr.hpp:700)  
==15994==    by 0x438BF9: main (Epetra_KSPEx.cpp:169)  
==15994==  
==15994== Invalid read of size 4  
==15994==    at 0x2B01C5C8: PetscObjectDestroy (destroy.c:71)  
==15994==    by 0x2B01E109: PetscObjectRegisterDestroyAll (destroy.c:251)  
==15994==    by 0x2B051F96: PetscFinalize (pinit.c:1141)  
==15994==    by 0x446D8D: Belos::PETScSolMgr<double, Epetra_MultiVector, Epetra_Operator>::solve() (BelosPETScSolMgr.hpp:711)  
==15994==    by 0x438BF9: main (Epetra_KSPEx.cpp:169)  
==15994==  Address 0x3604b1a0 is 1,600 bytes inside a block of size 2,356 free'd 
==15994==    at 0x4A07430: free (vg_replace_malloc.c:446)  
==15994==    by 0x2B000E24: PetscFreeAlign (mal.c:72)  
==15994==    by 0x2B004000: PetscTrFreeDefault (mtr.c:315) 
==15994==    by 0x2B0D4143: PetscViewerDestroy (view.c:108)  
==15994==    by 0x2B0D48B3: PetscViewerAndFormatDestroy (view.c:167)  
==15994==    by 0x2C112063: KSPMonitorCancel (itfunc.c:1807)  
==15994==    by 0x2C109C5C: KSPDestroy (itfunc.c:991)  
==15994==    by 0x446C53: Belos::PETScSolMgr<double, Epetra_MultiVector, Epetra_Operator>::solve() (BelosPETScSolMgr.hpp:700)  
==15994==    by 0x438BF9: main (Epetra_KSPEx.cpp:169)  
==15994==  
[0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------  
[0]PETSC ERROR: Corrupt argument: http://www.mcs.anl.gov/petsc/documentation/faq.html#valgrind 
[0]PETSC ERROR: Invalid type of object: Parameter # 1  
[0]PETSC ERROR: See http://www.mcs.anl.gov/petsc/documentation/faq.html for trouble shooting.  
[0]PETSC ERROR: Petsc Development GIT revision: pre-tsfc-1149-gca43db0  GIT Date: 2016-04-06 00:18:04 -0500  
[0]PETSC ERROR: Unknown Name on a arch-linux2-c-debug named s995692.srn.sandia.gov by amklinv Wed Apr  6 13:14:40 2016  
[0]PETSC ERROR: Configure options --download-xsdk --prefix=/home/amklinv/IDEAS/xSDKTest/xsdk-install --with-boost-dir=/projects/install/rhel6-x86_64/sems/tpl/boost/1.59.0/intel/16.0.1/base --with-cxx-dialect=C++11 --download-hdf5 --download-netcdf --download-exodusii --download-metis --download-superlu_dist --download-parmetis --download-hypre --download-trilinos --with-cxx-dialect=C++11 --download-xsdktrilinos  
[0]PETSC ERROR: #1 PetscObjectDestroy() line 71 in /home/amklinv/IDEAS/xSDKTest/installxSDK/xsdk/petsc/src/sys/objects/destroy.c  
[0]PETSC ERROR: #2 PetscObjectRegisterDestroyAll() line 251 in /home/amklinv/IDEAS/xSDKTest/installxSDK/xsdk/petsc/src/sys/objects/destroy.c  
[0]PETSC ERROR: #3 PetscFinalize() line 1141 in /home/amklinv/IDEAS/xSDKTest/installxSDK/xsdk/petsc/src/sys/objects/pinit.c

If I comment out that segment of the code, PETSc and valgrind don't report any errors.  Is PETSc unhappy that the Viewer is being created without being destroyed?

**Comment by BarrySmith** [comment]
I will debug this once I get everything installed. Likely I made a mistake, but since you are the first to get this to actually run you found the problem first.

   Barry

**Comment by amklinv** [comment]
Thanks Barry!  Just be aware that you have to increase the Belos verbosity level for the problem to show up.  (I might have the improved example committed by the time you take a look at this, in which the verbosity level has been increased.)

**Comment by BarrySmith** [comment]
I got everything built finally and can reproduce the problem.

**Pull request closed without merging**
